-- Create interview_feedbacks table for multi-feedback support
CREATE TABLE interview_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    interview_id BIGINT NOT NULL REFERENCES interviews(id),
    submitted_by BIGINT NOT NULL,
    interviewer_name VARCHAR(255),
    feedback TEXT NOT NULL,
    rating INT,
    communication_skills INT,
    technical_skills INT,
    cultural_fit INT,
    overall_impression TEXT,
    recommendation VARCHAR(50) NOT NULL,
    next_steps TEXT,
    technical_assessment TEXT,
    candidate_questions TEXT,
    interviewer_notes TEXT,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_interview_feedback_interviewer UNIQUE (interview_id, submitted_by)
);

CREATE INDEX idx_interview_feedbacks_interview ON interview_feedbacks(interview_id);
CREATE INDEX idx_interview_feedbacks_submitted_by ON interview_feedbacks(submitted_by);

-- Migrate existing feedback data from interviews table into interview_feedbacks
INSERT INTO interview_feedbacks (tenant_id, interview_id, submitted_by, feedback, rating,
    communication_skills, technical_skills, cultural_fit, overall_impression,
    recommendation, next_steps, technical_assessment, candidate_questions,
    interviewer_notes, submitted_at)
SELECT i.tenant_id, i.id, COALESCE(i.interviewer_id, i.created_by, 1), i.feedback, i.rating,
    i.communication_skills, i.technical_skills, i.cultural_fit, i.overall_impression,
    COALESCE(i.recommendation, 'CONSIDER'), i.next_steps, i.technical_assessment,
    i.candidate_questions, i.interviewer_notes,
    COALESCE(i.feedback_submitted_at, i.completed_at, CURRENT_TIMESTAMP)
FROM interviews i
WHERE i.feedback IS NOT NULL;
